codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 0%
        base: auto
        branches:
          - main
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - backend
        paths:
          - backend

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
